Dergipark\WorkflowBundle\Entity\JournalWorkflowSetting:
  type: entity
  table: bc_wf_journal_wf_setting
  repositoryClass: Dergipark\WorkflowBundle\Entity\JournalWorkflowSettingRepository
  cache:
    usage: NONSTRICT_READ_WRITE
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  manyToOne:
    journal:
      targetEntity: Ojs\JournalBundle\Entity\Journal
      joinColumn:
        name: journal_id
        referencedColumnName: id
  fields:
    doubleBlind:
      type: boolean
      column: double_blind
      options:
          default: true
      nullable: true
    reviewerWaitDay:
      type: integer
      column: reviewer_wait_day
      options:
        default: 15
      nullable: false
